baseurl = "https://blog.kartikpatekar.com"
title = "Thoughts on track"
theme = "cleanwhite"
languageCode = "en-us"
preserveTaxonomyNames = true
hasCJKLanguage = true

[services]
  [services.disqus]
    shortname = "YOUR_DISQUS_SHORTNAME"
  [services.googleAnalytics]
    id = "YOUR_GA_ID"

[pagination]
  pagerSize = 5

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/home-bg-jeep.jpg"
  SEOTitle = "Your Blog Title | Your Name Blog"
  description = "Your description here"
  keyword = "your, keywords, here"
  slogan = "My attempts at understanding economics research"
  upstreamAttribution = true

  image_404 = "img/404-bg.jpg"
  title_404 = "Page not found"
  omit_categories = false

  # Disabled by default for security
  page_view_counter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # Disabled until properly configured
  algolia_search = false
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "I am a Economics PhD at Boston University. I am broadly intersted in applied microeconomics. My specific interest is in studying technology adoption in developing countries."
  sidebar_avatar = "general/KP_Photo.png"

  featured_tags = true 
  featured_condition_size = 1 

  # Analytics - disabled by default
  ba_track_id = ""
  
  # Comment systems - disabled by default
  disqus_proxy = ""
  disqus_site = ""
  twikoo_env_id = ""
  artalk_enable = false
  artalk_server = ""
  artalk_site = ""

  # Disabled for security
  reward = false
  
  friends = true
  bookmarks = false
  about_me = true
  last_posts = true

  [params.social]
  rss = true 
  email = "your-email@example.com"
  linkedin = "https://www.linkedin.com/in/yourprofile"
  stackoverflow = "https://stackoverflow.com/users/yourid"
  github = "https://github.com/yourusername"
  wechat = "img/wechat-qr-placeholder.png"

  # Safe external links
  [[params.friend_link]]
  title = "Example Blog"
  href = "https://example.com"

  [[params.bookmark_link]]
  title = "Example Site"
  href = "https://example.com"
  
  [[params.additional_menus]]
  title = "ARCHIVE"
  href = "/archive/"
  [[params.additional_menus]]
  title = "NOTES"
  href = "/notes/"
  [[params.additional_menus]]
  title = "ABOUT"
  href = "/about/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false  # Changed to false for security
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = false  # Disabled for security

[mediaTypes]
  [mediaTypes.'font/woff']
    suffixes = ['woff']
  [mediaTypes.'font/woff2']
    suffixes = ['woff2']